# Generated by Django 2.0.1 on 2018-01-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180128_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
